// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: server/proto/sentinel.proto

package sentinelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentEnrollmentService_Enroll_FullMethodName = "/sentinel.v1.AgentEnrollmentService/Enroll"
)

// AgentEnrollmentServiceClient is the client API for AgentEnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentEnrollment handles initial agent registration
type AgentEnrollmentServiceClient interface {
	Enroll(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
}

type agentEnrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentEnrollmentServiceClient(cc grpc.ClientConnInterface) AgentEnrollmentServiceClient {
	return &agentEnrollmentServiceClient{cc}
}

func (c *agentEnrollmentServiceClient) Enroll(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, AgentEnrollmentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentEnrollmentServiceServer is the server API for AgentEnrollmentService service.
// All implementations must embed UnimplementedAgentEnrollmentServiceServer
// for forward compatibility.
//
// AgentEnrollment handles initial agent registration
type AgentEnrollmentServiceServer interface {
	Enroll(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error)
	mustEmbedUnimplementedAgentEnrollmentServiceServer()
}

// UnimplementedAgentEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentEnrollmentServiceServer struct{}

func (UnimplementedAgentEnrollmentServiceServer) Enroll(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentEnrollmentServiceServer) mustEmbedUnimplementedAgentEnrollmentServiceServer() {
}
func (UnimplementedAgentEnrollmentServiceServer) testEmbeddedByValue() {}

// UnsafeAgentEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentEnrollmentServiceServer will
// result in compilation errors.
type UnsafeAgentEnrollmentServiceServer interface {
	mustEmbedUnimplementedAgentEnrollmentServiceServer()
}

func RegisterAgentEnrollmentServiceServer(s grpc.ServiceRegistrar, srv AgentEnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentEnrollmentService_ServiceDesc, srv)
}

func _AgentEnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServiceServer).Enroll(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentEnrollmentService_ServiceDesc is the grpc.ServiceDesc for AgentEnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentEnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.AgentEnrollmentService",
	HandlerType: (*AgentEnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentEnrollmentService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/sentinel.proto",
}

const (
	AgentTelemetryService_StreamEvents_FullMethodName   = "/sentinel.v1.AgentTelemetryService/StreamEvents"
	AgentTelemetryService_CommandChannel_FullMethodName = "/sentinel.v1.AgentTelemetryService/CommandChannel"
)

// AgentTelemetryServiceClient is the client API for AgentTelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentTelemetry handles bidirectional event streaming and command delivery
type AgentTelemetryServiceClient interface {
	// Agent streams event batches to server; server acks
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, IngestResponse], error)
	// Server pushes commands to agent; agent responds with outcomes
	CommandChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, CommandRequest], error)
}

type agentTelemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTelemetryServiceClient(cc grpc.ClientConnInterface) AgentTelemetryServiceClient {
	return &agentTelemetryServiceClient{cc}
}

func (c *agentTelemetryServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentTelemetryService_ServiceDesc.Streams[0], AgentTelemetryService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_StreamEventsClient = grpc.BidiStreamingClient[EventBatch, IngestResponse]

func (c *agentTelemetryServiceClient) CommandChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, CommandRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentTelemetryService_ServiceDesc.Streams[1], AgentTelemetryService_CommandChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandResponse, CommandRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_CommandChannelClient = grpc.BidiStreamingClient[CommandResponse, CommandRequest]

// AgentTelemetryServiceServer is the server API for AgentTelemetryService service.
// All implementations must embed UnimplementedAgentTelemetryServiceServer
// for forward compatibility.
//
// AgentTelemetry handles bidirectional event streaming and command delivery
type AgentTelemetryServiceServer interface {
	// Agent streams event batches to server; server acks
	StreamEvents(grpc.BidiStreamingServer[EventBatch, IngestResponse]) error
	// Server pushes commands to agent; agent responds with outcomes
	CommandChannel(grpc.BidiStreamingServer[CommandResponse, CommandRequest]) error
	mustEmbedUnimplementedAgentTelemetryServiceServer()
}

// UnimplementedAgentTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTelemetryServiceServer struct{}

func (UnimplementedAgentTelemetryServiceServer) StreamEvents(grpc.BidiStreamingServer[EventBatch, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAgentTelemetryServiceServer) CommandChannel(grpc.BidiStreamingServer[CommandResponse, CommandRequest]) error {
	return status.Error(codes.Unimplemented, "method CommandChannel not implemented")
}
func (UnimplementedAgentTelemetryServiceServer) mustEmbedUnimplementedAgentTelemetryServiceServer() {}
func (UnimplementedAgentTelemetryServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTelemetryServiceServer will
// result in compilation errors.
type UnsafeAgentTelemetryServiceServer interface {
	mustEmbedUnimplementedAgentTelemetryServiceServer()
}

func RegisterAgentTelemetryServiceServer(s grpc.ServiceRegistrar, srv AgentTelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTelemetryService_ServiceDesc, srv)
}

func _AgentTelemetryService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentTelemetryServiceServer).StreamEvents(&grpc.GenericServerStream[EventBatch, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_StreamEventsServer = grpc.BidiStreamingServer[EventBatch, IngestResponse]

func _AgentTelemetryService_CommandChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentTelemetryServiceServer).CommandChannel(&grpc.GenericServerStream[CommandResponse, CommandRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_CommandChannelServer = grpc.BidiStreamingServer[CommandResponse, CommandRequest]

// AgentTelemetryService_ServiceDesc is the grpc.ServiceDesc for AgentTelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.AgentTelemetryService",
	HandlerType: (*AgentTelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AgentTelemetryService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CommandChannel",
			Handler:       _AgentTelemetryService_CommandChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/proto/sentinel.proto",
}

const (
	HealthService_Check_FullMethodName = "/sentinel.v1.HealthService/Check"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	Check(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	Check(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/sentinel.proto",
}
