// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: server/proto/sentinel.proto

package sentinelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_EVENT_TYPE_PROCESS       EventType = 1
	EventType_EVENT_TYPE_FILE          EventType = 2
	EventType_EVENT_TYPE_NETWORK       EventType = 3
	EventType_EVENT_TYPE_LOG           EventType = 4
	EventType_EVENT_TYPE_METRIC        EventType = 5
	EventType_EVENT_TYPE_VULNERABILITY EventType = 6
	EventType_EVENT_TYPE_CONTAINER     EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PROCESS",
		2: "EVENT_TYPE_FILE",
		3: "EVENT_TYPE_NETWORK",
		4: "EVENT_TYPE_LOG",
		5: "EVENT_TYPE_METRIC",
		6: "EVENT_TYPE_VULNERABILITY",
		7: "EVENT_TYPE_CONTAINER",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"EVENT_TYPE_PROCESS":       1,
		"EVENT_TYPE_FILE":          2,
		"EVENT_TYPE_NETWORK":       3,
		"EVENT_TYPE_LOG":           4,
		"EVENT_TYPE_METRIC":        5,
		"EVENT_TYPE_VULNERABILITY": 6,
		"EVENT_TYPE_CONTAINER":     7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_sentinel_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_server_proto_sentinel_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_sentinel_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_server_proto_sentinel_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED       CommandType = 0
	CommandType_COMMAND_TYPE_KILL_PROCESS      CommandType = 1
	CommandType_COMMAND_TYPE_BLOCK_IP          CommandType = 2
	CommandType_COMMAND_TYPE_UNBLOCK_IP        CommandType = 3
	CommandType_COMMAND_TYPE_ISOLATE_HOST      CommandType = 4
	CommandType_COMMAND_TYPE_UNISOLATE_HOST    CommandType = 5
	CommandType_COMMAND_TYPE_QUARANTINE_FILE   CommandType = 6
	CommandType_COMMAND_TYPE_UNQUARANTINE_FILE CommandType = 7
	CommandType_COMMAND_TYPE_RUN_SCRIPT        CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_KILL_PROCESS",
		2: "COMMAND_TYPE_BLOCK_IP",
		3: "COMMAND_TYPE_UNBLOCK_IP",
		4: "COMMAND_TYPE_ISOLATE_HOST",
		5: "COMMAND_TYPE_UNISOLATE_HOST",
		6: "COMMAND_TYPE_QUARANTINE_FILE",
		7: "COMMAND_TYPE_UNQUARANTINE_FILE",
		8: "COMMAND_TYPE_RUN_SCRIPT",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":       0,
		"COMMAND_TYPE_KILL_PROCESS":      1,
		"COMMAND_TYPE_BLOCK_IP":          2,
		"COMMAND_TYPE_UNBLOCK_IP":        3,
		"COMMAND_TYPE_ISOLATE_HOST":      4,
		"COMMAND_TYPE_UNISOLATE_HOST":    5,
		"COMMAND_TYPE_QUARANTINE_FILE":   6,
		"COMMAND_TYPE_UNQUARANTINE_FILE": 7,
		"COMMAND_TYPE_RUN_SCRIPT":        8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_sentinel_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_server_proto_sentinel_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

type SystemFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                // "linux", "windows", "darwin"
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`                            // "amd64", "arm64"
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // e.g. "Ubuntu 22.04", "Windows 11 23H2"
	Kernel        string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MachineId     string                 `protobuf:"bytes,8,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // unique machine identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemFingerprint) Reset() {
	*x = SystemFingerprint{}
	mi := &file_server_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemFingerprint) ProtoMessage() {}

func (x *SystemFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemFingerprint.ProtoReflect.Descriptor instead.
func (*SystemFingerprint) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *SystemFingerprint) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemFingerprint) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemFingerprint) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemFingerprint) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemFingerprint) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SystemFingerprint) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemFingerprint) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *SystemFingerprint) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type EnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // single-use JWT enrollment token
	Fingerprint   *SystemFingerprint     `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_server_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollmentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollmentRequest) GetFingerprint() *SystemFingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *EnrollmentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentCert     []byte                 `protobuf:"bytes,2,opt,name=agent_cert,json=agentCert,proto3" json:"agent_cert,omitempty"`             // PEM-encoded agent TLS certificate
	AgentKey      []byte                 `protobuf:"bytes,3,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                // PEM-encoded agent private key
	CaCert        []byte                 `protobuf:"bytes,4,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`                      // PEM-encoded server CA certificate
	ServerAddress string                 `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"` // gRPC endpoint for telemetry streaming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_server_proto_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollmentResponse) GetAgentCert() []byte {
	if x != nil {
		return x.AgentCert
	}
	return nil
}

func (x *EnrollmentResponse) GetAgentKey() []byte {
	if x != nil {
		return x.AgentKey
	}
	return nil
}

func (x *EnrollmentResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *EnrollmentResponse) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          EventType              `protobuf:"varint,3,opt,name=type,proto3,enum=sentinel.v1.EventType" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // flexible key-value payload
	RawData       []byte                 `protobuf:"bytes,6,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`                                                          // optional raw log line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_server_proto_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Event) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type EventBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events         []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // for ordered replay from buffer
	Compressed     bool                   `protobuf:"varint,4,opt,name=compressed,proto3" json:"compressed,omitempty"`                               // if true, events payload is gzip-compressed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_server_proto_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *EventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *EventBatch) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AckedSequence uint64                 `protobuf:"varint,2,opt,name=acked_sequence,json=ackedSequence,proto3" json:"acked_sequence,omitempty"` // highest sequence number server accepted
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_server_proto_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestResponse) GetAckedSequence() uint64 {
	if x != nil {
		return x.AckedSequence
	}
	return 0
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type           CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=sentinel.v1.CommandType" json:"type,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"pid": "1234"}, {"ip": "1.2.3.4"}
	IssuedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // default 30
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_server_proto_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CommandRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CommandRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CommandRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_server_proto_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_server_proto_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSince   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	Components    map[string]string      `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {"opensearch": "healthy", "nats": "healthy"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_proto_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *HealthResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_server_proto_sentinel_proto protoreflect.FileDescriptor

const file_server_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x1bserver/proto/sentinel.proto\x12\vsentinel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\x11SystemFingerprint\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\rR\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"machine_id\x18\b \x01(\tR\tmachineId\"\x90\x01\n" +
	"\x11EnrollmentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12@\n" +
	"\vfingerprint\x18\x02 \x01(\v2\x1e.sentinel.v1.SystemFingerprintR\vfingerprint\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\"\xab\x01\n" +
	"\x12EnrollmentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_cert\x18\x02 \x01(\fR\tagentCert\x12\x1b\n" +
	"\tagent_key\x18\x03 \x01(\fR\bagentKey\x12\x17\n" +
	"\aca_cert\x18\x04 \x01(\fR\x06caCert\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\"\xa6\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.sentinel.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\x06fields\x18\x05 \x03(\v2\x1e.sentinel.v1.Event.FieldsEntryR\x06fields\x12\x19\n" +
	"\braw_data\x18\x06 \x01(\fR\arawData\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\n" +
	"EventBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.sentinel.v1.EventR\x06events\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x12\x1e\n" +
	"\n" +
	"compressed\x18\x04 \x01(\bR\n" +
	"compressed\"i\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0eacked_sequence\x18\x02 \x01(\x04R\rackedSequence\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xcb\x02\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.sentinel.v1.CommandTypeR\x04type\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.sentinel.v1.CommandRequest.ParametersEntryR\n" +
	"parameters\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\rR\x0etimeoutSeconds\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x0f\n" +
	"\rHealthRequest\"\x8d\x02\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\fuptime_since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12K\n" +
	"\n" +
	"components\x18\x04 \x03(\v2+.sentinel.v1.HealthResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xcf\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_PROCESS\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_FILE\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_NETWORK\x10\x03\x12\x12\n" +
	"\x0eEVENT_TYPE_LOG\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_METRIC\x10\x05\x12\x1c\n" +
	"\x18EVENT_TYPE_VULNERABILITY\x10\x06\x12\x18\n" +
	"\x14EVENT_TYPE_CONTAINER\x10\a*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05*\xa5\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_KILL_PROCESS\x10\x01\x12\x19\n" +
	"\x15COMMAND_TYPE_BLOCK_IP\x10\x02\x12\x1b\n" +
	"\x17COMMAND_TYPE_UNBLOCK_IP\x10\x03\x12\x1d\n" +
	"\x19COMMAND_TYPE_ISOLATE_HOST\x10\x04\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_UNISOLATE_HOST\x10\x05\x12 \n" +
	"\x1cCOMMAND_TYPE_QUARANTINE_FILE\x10\x06\x12\"\n" +
	"\x1eCOMMAND_TYPE_UNQUARANTINE_FILE\x10\a\x12\x1b\n" +
	"\x17COMMAND_TYPE_RUN_SCRIPT\x10\b2c\n" +
	"\x16AgentEnrollmentService\x12I\n" +
	"\x06Enroll\x12\x1e.sentinel.v1.EnrollmentRequest\x1a\x1f.sentinel.v1.EnrollmentResponse2\xb2\x01\n" +
	"\x15AgentTelemetryService\x12H\n" +
	"\fStreamEvents\x12\x17.sentinel.v1.EventBatch\x1a\x1b.sentinel.v1.IngestResponse(\x010\x01\x12O\n" +
	"\x0eCommandChannel\x12\x1c.sentinel.v1.CommandResponse\x1a\x1b.sentinel.v1.CommandRequest(\x010\x012Q\n" +
	"\rHealthService\x12@\n" +
	"\x05Check\x12\x1a.sentinel.v1.HealthRequest\x1a\x1b.sentinel.v1.HealthResponseB9Z7github.com/sentinel-io/sentinel/server/proto/sentinelpbb\x06proto3"

var (
	file_server_proto_sentinel_proto_rawDescOnce sync.Once
	file_server_proto_sentinel_proto_rawDescData []byte
)

func file_server_proto_sentinel_proto_rawDescGZIP() []byte {
	file_server_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_server_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_sentinel_proto_rawDesc), len(file_server_proto_sentinel_proto_rawDesc)))
	})
	return file_server_proto_sentinel_proto_rawDescData
}

var file_server_proto_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_proto_sentinel_proto_goTypes = []any{
	(EventType)(0),                // 0: sentinel.v1.EventType
	(Severity)(0),                 // 1: sentinel.v1.Severity
	(CommandType)(0),              // 2: sentinel.v1.CommandType
	(*SystemFingerprint)(nil),     // 3: sentinel.v1.SystemFingerprint
	(*EnrollmentRequest)(nil),     // 4: sentinel.v1.EnrollmentRequest
	(*EnrollmentResponse)(nil),    // 5: sentinel.v1.EnrollmentResponse
	(*Event)(nil),                 // 6: sentinel.v1.Event
	(*EventBatch)(nil),            // 7: sentinel.v1.EventBatch
	(*IngestResponse)(nil),        // 8: sentinel.v1.IngestResponse
	(*CommandRequest)(nil),        // 9: sentinel.v1.CommandRequest
	(*CommandResponse)(nil),       // 10: sentinel.v1.CommandResponse
	(*HealthRequest)(nil),         // 11: sentinel.v1.HealthRequest
	(*HealthResponse)(nil),        // 12: sentinel.v1.HealthResponse
	nil,                           // 13: sentinel.v1.Event.FieldsEntry
	nil,                           // 14: sentinel.v1.CommandRequest.ParametersEntry
	nil,                           // 15: sentinel.v1.HealthResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_server_proto_sentinel_proto_depIdxs = []int32{
	3,  // 0: sentinel.v1.EnrollmentRequest.fingerprint:type_name -> sentinel.v1.SystemFingerprint
	0,  // 1: sentinel.v1.Event.type:type_name -> sentinel.v1.EventType
	16, // 2: sentinel.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	13, // 3: sentinel.v1.Event.fields:type_name -> sentinel.v1.Event.FieldsEntry
	6,  // 4: sentinel.v1.EventBatch.events:type_name -> sentinel.v1.Event
	2,  // 5: sentinel.v1.CommandRequest.type:type_name -> sentinel.v1.CommandType
	14, // 6: sentinel.v1.CommandRequest.parameters:type_name -> sentinel.v1.CommandRequest.ParametersEntry
	16, // 7: sentinel.v1.CommandRequest.issued_at:type_name -> google.protobuf.Timestamp
	16, // 8: sentinel.v1.CommandResponse.completed_at:type_name -> google.protobuf.Timestamp
	16, // 9: sentinel.v1.HealthResponse.uptime_since:type_name -> google.protobuf.Timestamp
	15, // 10: sentinel.v1.HealthResponse.components:type_name -> sentinel.v1.HealthResponse.ComponentsEntry
	4,  // 11: sentinel.v1.AgentEnrollmentService.Enroll:input_type -> sentinel.v1.EnrollmentRequest
	7,  // 12: sentinel.v1.AgentTelemetryService.StreamEvents:input_type -> sentinel.v1.EventBatch
	10, // 13: sentinel.v1.AgentTelemetryService.CommandChannel:input_type -> sentinel.v1.CommandResponse
	11, // 14: sentinel.v1.HealthService.Check:input_type -> sentinel.v1.HealthRequest
	5,  // 15: sentinel.v1.AgentEnrollmentService.Enroll:output_type -> sentinel.v1.EnrollmentResponse
	8,  // 16: sentinel.v1.AgentTelemetryService.StreamEvents:output_type -> sentinel.v1.IngestResponse
	9,  // 17: sentinel.v1.AgentTelemetryService.CommandChannel:output_type -> sentinel.v1.CommandRequest
	12, // 18: sentinel.v1.HealthService.Check:output_type -> sentinel.v1.HealthResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_server_proto_sentinel_proto_init() }
func file_server_proto_sentinel_proto_init() {
	if File_server_proto_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_sentinel_proto_rawDesc), len(file_server_proto_sentinel_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_server_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_server_proto_sentinel_proto_depIdxs,
		EnumInfos:         file_server_proto_sentinel_proto_enumTypes,
		MessageInfos:      file_server_proto_sentinel_proto_msgTypes,
	}.Build()
	File_server_proto_sentinel_proto = out.File
	file_server_proto_sentinel_proto_goTypes = nil
	file_server_proto_sentinel_proto_depIdxs = nil
}
